### ISSUE TITLE
Not working in colab.

### ISSUE THREAD

**Issue by darkon12** [camenduru/zero123plus-colab#2]
After loading diffusion_pytorch_model.bin the log says:

diffusion_pytorch_model.bin: 100% 1.73G/1.73G [00:35<00:00, 49.2MB/s]
Fetching 16 files: 100% 16/16 [00:37<00:00,  2.32s/it]
Loading pipeline components...: 100% 8/8 [00:09<00:00,  1.23s/it]
Traceback (most recent call last):
  File "/content/zero123plus-hf/gradio_app.py", line 204, in <module>
    fire.Fire(run_demo)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/zero123plus-hf/gradio_app.py", line 155, in run_demo
    input_image = gr.Image(type='pil', image_mode='RGBA', height=320, label='Input image', tool=None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'tool'

**Comment by camenduru** [comment]
thanks for the info ❤ please try again

**Comment by darkon12** [comment]
Thanks a lot, working now.
